<#
.SYNOPSIS
  atlas Phase 0 deploy — provisions Cosmos DB, Static Web App, App Insights.
#>

[CmdletBinding()]
param(
  [string]$SubscriptionName = 'Visual Studio Enterprise Subscription',
  [string]$ResourceGroupName = 'atlas-rg',
  [string]$Location = 'swedencentral',
  [string]$DeploymentName = "atlas-phase0-$(Get-Date -Format 'yyyyMMddHHmm')",
  [switch]$SkipWhatIf,
  [switch]$DryRun
)

$ErrorActionPreference = 'Stop'
$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$bicepFile = Join-Path $scriptRoot 'main.bicep'
$bicepParamFile = Join-Path $scriptRoot 'main.bicepparam'
$projectRoot = Split-Path -Parent $scriptRoot
$envFile = Join-Path $projectRoot '.env'

function Write-Step($m) { Write-Host ""; Write-Host "==> $m" -ForegroundColor Cyan }

# 1. Preflight
Write-Step 'Preflight'
az account set --subscription $SubscriptionName 1>$null
$sub = az account show --query "{name:name,id:id,user:user.name}" -o json | ConvertFrom-Json
if ($sub.name -ne $SubscriptionName) {
  throw "Wrong subscription. Expected '$SubscriptionName', got '$($sub.name)'."
}
Write-Host "  Subscription: $($sub.name)"
Write-Host "  Sub ID:       $($sub.id)"

$ownerObjectId = az ad signed-in-user show --query id -o tsv
if (-not $ownerObjectId) { throw "Could not resolve signed-in user object ID." }
Write-Host "  Owner objectId: $ownerObjectId"
Write-Host "  Region:       $Location"
Write-Host "  RG:           $ResourceGroupName"

# 2. Resource group
Write-Step 'Resource group'
$rgExists = az group exists --name $ResourceGroupName | ConvertFrom-Json
if ($rgExists) {
  Write-Host "  Already exists."
} else {
  Write-Host "  Creating $ResourceGroupName..."
  az group create --name $ResourceGroupName --location $Location `
    --tags project=atlas environment=production managedBy=bicep 1>$null
}

# 3. What-if (optional)
if (-not $SkipWhatIf) {
  Write-Step 'Dry run'
  az deployment group what-if `
    --resource-group $ResourceGroupName `
    --template-file $bicepFile `
    --parameters $bicepParamFile `
    --parameters ownerObjectId=$ownerObjectId 2>&1 | ForEach-Object { Write-Host $_ }
  if ($DryRun) { Write-Host "DryRun done." -ForegroundColor Yellow; return }
  Write-Host ""
  $confirm = Read-Host "Proceed? (y/N)"
  if ($confirm -ne 'y' -and $confirm -ne 'Y') {
    Write-Host "Aborted." -ForegroundColor Yellow; return
  }
}

# 4. Deploy
Write-Step "Deploying $DeploymentName"
az deployment group create `
  --resource-group $ResourceGroupName `
  --name $DeploymentName `
  --template-file $bicepFile `
  --parameters $bicepParamFile `
  --parameters ownerObjectId=$ownerObjectId `
  --output none

if ($LASTEXITCODE -ne 0) { throw "Deployment failed." }

# 5. Fetch outputs
$outputsJson = az deployment group show `
  --resource-group $ResourceGroupName `
  --name $DeploymentName `
  --query properties.outputs `
  --output json
$outputs = $outputsJson | ConvertFrom-Json

# 6. Write .env
Write-Step "Writing $envFile"
$lines = @(
  "# Generated by atlas/infrastructure/deploy.ps1"
  "AZURE_SUBSCRIPTION_ID=$($sub.id)"
  "AZURE_RESOURCE_GROUP=$ResourceGroupName"
  "AZURE_LOCATION=$Location"
  ""
  "COSMOS_ENDPOINT=$($outputs.cosmosEndpoint.value)"
  "COSMOS_ACCOUNT_ID=$($outputs.cosmosAccountId.value)"
  "COSMOS_DATABASE=atlas"
  ""
  "SWA_NAME=$($outputs.swaName.value)"
  "SWA_HOSTNAME=$($outputs.swaHostname.value)"
  "SWA_ID=$($outputs.swaId.value)"
  ""
  "APPLICATIONINSIGHTS_CONNECTION_STRING=$($outputs.appInsightsConnectionString.value)"
  ""
  "# Reused from foundryLab"
  "FOUNDRY_PROJECT_ENDPOINT=https://foundrylab-aiservices.services.ai.azure.com/api/projects/foundrylab"
  "FOUNDRY_AOAI_ENDPOINT=https://foundrylab-aiservices.cognitiveservices.azure.com/"
  "FOUNDRY_DEPLOYMENT=gpt-4o-mini"
  ""
  "ATLAS_USER_ID=sam"
)
$lines -join "`n" | Set-Content -Path $envFile -Encoding utf8

Write-Step 'Done'
Write-Host "  Cosmos:      $($outputs.cosmosEndpoint.value)"
Write-Host "  SWA host:    https://$($outputs.swaHostname.value)"
